### ISSUE TITLE
Support for `$meta: 'textScore'`

### ISSUE THREAD

**Issue by jgutix** [loopbackio/loopback-connector-mongodb#577]
## Suggestion
I assume `$meta: 'textScore'` is not supported, so far I tried the following:
```
let references = await this.referenceRepository.find(
    {
      fields: {name: true, city: true, /*score: {meta: 'textScore'}*/}, //Error: Type '{ meta: string; }' is not assignable to type 'true'.
      where: {
        '$text': {search: param.reference},
        // score: {meta: 'textScore'} //500 MongoError: unknown operator: $meta
      },

      /*order: {
        score: {meta: 'textScore'} //Error: Type '{ score: { meta: string; }; }' is not assignable to type 'string[]'.
      }*/
    }, /*{score: {meta: 'textScore'}}*/); // doesnt work
```
Mostly what stop the implementation here is the type constraint on fields and order filters.

As a workaround I had to access directly to the mongodb's driver as shown here: https://gist.github.com/jgutix/71cbb8a9f5946ecd57328862154e3c15

## Use Cases
Most of the time will go hand on hand with the use of `$text` search

## Examples
Following the syntax from mongo driver:
```
let references = await this.referenceRepository.find(
    {
      fields: {name: true, city: true, score: {meta: 'textScore'}}, 
      where: {
        '$text': {search: param.reference},
      },
      order: {
        score: {meta: 'textScore'},
      }
    },);
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by agnes512** [comment]
We're working on `Repository.execute` method that allows raw queries, see https://github.com/strongloop/loopback-next/issues/3342. I think once it is implemented, it would be a good workaround.

**Comment by agnes512** [comment]
See https://loopback.io/doc/en/lb4/Executing-database-commands.html
