### ISSUE TITLE
UpsertWithWhere with collection().update operation

### ISSUE THREAD

**Issue by jamesjjk** [loopbackio/loopback-connector-mongodb#593]
## Suggestion

Why not support upsertWithWhere with an update operation and ```upsert: true``` option set

## Use Cases

Atomic update or creation of a document when using upsertWithWhere operations in loopback

## Examples

Currently this is not supported by the connector, whilst it likely should be.

**Comment by mrbatista** [comment]
@jamesjjk see #563

**Comment by jamesjjk** [comment]
@mrbatista 

Appreciated but I don't understand why this would have to be a transactional operation? Isn't that a bit overkill, considering mongoDB supports: "findAndModify" operation with "new" and "upsert" options that would atomically update OR insert the document and return the updated or inserted document?

https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/#db.collection.findAndModify
