### ISSUE TITLE
SPIKE: Connector level model validation

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback-connector-mongodb#599]
Follow up of https://github.com/strongloop/loopback-next/issues/3456.

Find out what it takes to implement model validation at the connector level. We may eventually do it for other connectors as well.

## Acceptance criteria

- [ ] Make a note of any unexpected challenges
- [ ] Develop a general direction about how we want to go with the implementation
- [ ] Create follow up task(s)

**Comment by jannyHou** [comment]
Discussion within team:
- We may need more details about the user scenarios and why need connector level validation
- What would be the technique  burden for developers 
- It will introduce new responsibility for connector developers
