### ISSUE TITLE
Custom field name doesn't work on property that is an array of a custom object / model

### ISSUE THREAD

**Issue by joewstroman** [loopbackio/loopback-connector-mongodb#604]
Hello all, 
I'm new to loopback but I think I may have found a bug. I have a document that has a list of other documents inside of it. With the strict option enabled the only fields that show up in the nested documents are those that match the property names exactly.

## Steps to reproduce

Shopping Cart
```javascript
@model({
  settings: {
    mongodb: {collection: 'collection1'}
  }
})
export class ShoppingCart extends Entity {
  @property({
    type: 'string',
    id: true,
    mongodb: {dataType: 'ObjectId'}
  })
  _id?: string;

  @property({
    type: 'array',
    itemType: Item
  })
  items: Item[];

  constructor(data?: Partial<Accident>) {
    super(data);
  }
}

@model()
export class Item extends Entity {
  @property()
  index: number;

  // this works
  @property({
    type: 'string',
  })
  qr_code: string;

  // this does not
  @property({
    type: 'string',
    mongodb: {
      fieldName: 'qr_code'
    },
  })
  code: string;
}
```

## Current Behavior

The fieldname property does not work in the array of `Item` Elements and the property is ignored on GET requests, but if the property name matches exactly it will work. The fieldname mapping on properties in the ShoppingCart model works (as expected).

## Expected Behavior

The fieldname property should allow the custom mapping in an array like it does everywhere else.

## Additional information

darwin x64 12.8.1
├── @loopback/boot@3.1.1
├── @loopback/core@2.13.0
├── @loopback/repository@3.2.1
├── @loopback/rest@9.1.0
├── @loopback/rest-explorer@3.0.4
├── @loopback/service-proxy@3.0.4
└── loopback-connector-mongodb@5.4.0

## Related Issues

I did not find anything related to this specifically.

**Comment by joewstroman** [comment]
Figured it out, item type had to be object. 

Note to self: Read the docs carefully

**Comment by joewstroman** [comment]
I changed the `items` property definition to 

```javascript
@property.array(Item)
items: Item[];
```

which is provided in some of the documentation but also doesn't work.

**Comment by joewstroman** [comment]
I added this:

https://github.com/joewstroman/loopback-connector-mongodb/commit/06b2c235800ee87c80b65a6fadc5891221fad20d

and used the property decorator like so:

```javascript
  @property.array(Item, {name: 'Item'})
  Items?: Item[];
```

and that made things work as expected.

**Comment by agnes512** [comment]
I am able to create array property with both definitions:
```
  @property({
    type: 'array',
    itemType: Book,
  })
  books?: Book[];

  @property.array(Book, {name: 'Book'})
  books?: Book[];
```

Glad to see that the second one works for you.

**Comment by joewstroman** [comment]
The issue is that if you don't add this: https://github.com/joewstroman/loopback-connector-mongodb/commit/06b2c235800ee87c80b65a6fadc5891221fad20d

the custom field names won't be mapped, when you query for the data.
