### ISSUE TITLE
db name is always admin if url is used without db

### ISSUE THREAD

**Issue by nflaig** [loopbackio/loopback-connector-mongodb#610]
## Steps to reproduce

- Set `url` parameter in connection properties to `mongodb://localhost:27017`
- Set `database` parameter to `mydb`

## Current Behavior

It will use `admin` as database

## Expected Behavior

It should use `mydb` as database

## Additional information

In the connector it checks if the `dbName` is in the url ([mongodb.js#L338](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L338)) and if not it should use `settings.database` but this is does not quite work because in the url will always be a database, the mongo driver will always set `admin` as default in the url if no database is specified ([url_parser.js#L377](https://github.com/mongodb/node-mongodb-native/blob/3.6/lib/url_parser.js#L377))

**Comment by dhmlau** [comment]
@nflaig, it sounds like a bug. Would you be interested to submit a PR?

**Comment by nflaig** [comment]
@dhmlau sure I can look into it

**Comment by kmaher9** [comment]
was this looked in to? currently experiencing same bug as described in steps to reproduce

**Comment by achrinza** [comment]
Hi @kmaher9 @nflaig, could you please verify if #637 fixes the issue?

**Comment by nflaig** [comment]
@achrinza thx for taking a look and providing a fix for the issue, I just reviewed the PR
