### ISSUE TITLE
readPreferenceTags not working

### ISSUE THREAD

**Issue by manichandu1998** [loopbackio/loopback-connector-mongodb#612]
## Steps to reproduce

- Provide readPreferenceTags in connection URL (mongodb://host/db?replicaSet=replicaSetName&readPreference=secondary&readPreferenceTags=tag1&readPreferenceTags=)
- Create a mongo Replica set with multiple nodes and the nodes having at least two different tags.

## Current Behaviour

- Read queries going into other replicas, the filtering due to tags isn't happening. 

## Expected Behaviour

- Read queries to go to the replica with the correct tag if it is available as provided in the connection URL

## Additional information
platform - linux, arch - x64, node version - 8.11.3

Loopback packages used:

- loopback@3.26.0
- loopback-connector-mongodb@4.2.0
- loopback-boot@2.28.0
- loopback-component-explorer@6.4.0
- loopback-connector-mysql@5.4.1
- loopback-datatype-objectid@1.0.5

**Comment by utkarshrathore** [comment]
I'm also facing this issue from a long time. It's extremely pertinent to have this issue resolved soon as it creates unexpected and uneven load on the cluster.
